return {
  "folke/which-key.nvim",
  opts = {
    icons = {
      rules = {
        { pattern = "可读性", icon = "󰊰 ", color = "blue" },
        { pattern = "优化", icon = " ", color = "green" },
        { pattern = "总结", icon = " ", color = "cyan" },
        { pattern = "解释", icon = "󰘦 ", color = "orange" },
        { pattern = "修复", icon = "  ", color = "red" },
        { pattern = "测试", icon = " ", color = "azure" },
        { pattern = "对话", icon = "󱜺 ", color = "green" },
        { pattern = "刷新", icon = " ", color = "yellow" },
        { pattern = "聚焦", icon = "󰋱 ", color = "purple" },
        { pattern = "模型", icon = " ", color = "grey" },
        { pattern = "仓库", icon = " ", color = "cyan" },
        { pattern = "任务", icon = "󰑮 ", color = "cyan" },
        { pattern = "书签", icon = "󰃀 ", color = "purple" },
        { pattern = "历史", icon = "󰋚 ", color = "yellow" },
        { pattern = "AI", icon = "󱙺 ", color = "green" },
        { pattern = "编辑", icon = " ", color = "blue" },
        { pattern = "清除", icon = "󰃢 ", color = "red" },
        { pattern = "重构", icon = "󰑌 ", color = "orange" },
        { pattern = "审查", icon = "󰍉 ", color = "blue" },
        { pattern = "架构", icon = "󰠮 ", color = "purple" },
        { pattern = "安全", icon = "󰒃 ", color = "red" },
        { pattern = "语言", icon = "󰗀 ", color = "cyan" },
      },
    },
    spec = {
      { "<leader>a", group = "AI助手" },
      { "<leader>c", group = "代码操作" },
      { "<leader>cc", group = "Copilot对话" },
      { "<leader>f", group = "文件操作" },
      { "<leader>g", group = "Git操作" },
      { "<leader>h", group = "书签管理" },
      { "<leader>s", group = "搜索查找" },
      { "<leader>t", group = "测试相关" },
      { "<leader>u", group = "撤销操作" },
      { "<leader>w", group = "窗口管理" },
      { "<leader>x", group = "诊断修复" },
      { "<leader>b", group = "缓冲区" },
      { "<leader>q", group = "退出操作" },
      { "<leader>o", group = "选项设置" },
      { "<leader>d", group = "调试相关" },
      { "<leader>r", group = "重构运行" },
      { "<leader>n", group = "新建项目" },
      { "<leader>l", group = "LaTeX操作" },
      { "<leader>L", group = "LSP功能" },
      
      -- 覆盖 LazyVim 默认按键描述
      { "<leader>e", desc = "文件浏览器" },
      { "<leader>E", desc = "当前目录浏览器" },
      { "<leader>K", desc = "关键词帮助" },
      { "<leader>S", desc = "临时缓冲区" },
      { "<leader>y", desc = "符号大纲" },
      { "<leader>,", desc = "切换缓冲区" },
      { "<leader>-", desc = "水平分割" },
      { "<leader>.", desc = "临时缓冲区开关" },
      { "<leader>/", desc = "项目搜索" },
      { "<leader>:", desc = "命令历史" },
      { "<leader>?", desc = "快捷键帮助" },
      { "<leader>`", desc = "切换其他缓冲区" },
      { "<leader>|", desc = "垂直分割" },
      { "<leader><bs>", desc = "删除缓冲区" },
      { "<leader><leader>", desc = "查找文件" },
      
      -- 缓冲区相关
      { "<leader>bb", desc = "切换缓冲区" },
      { "<leader>bd", desc = "删除缓冲区" },
      { "<leader>bD", desc = "删除其他缓冲区" },
      { "<leader>bl", desc = "缓冲区列表" },
      { "<leader>bn", desc = "下一个缓冲区" },
      { "<leader>bp", desc = "上一个缓冲区" },
      { "<leader>br", desc = "重新载入缓冲区" },
      
      -- 文件操作
      { "<leader>ff", desc = "查找文件" },
      { "<leader>fg", desc = "Git文件搜索" },
      { "<leader>fr", desc = "最近文件" },
      { "<leader>fn", desc = "新建文件" },
      { "<leader>fs", desc = "保存文件" },
      
      -- 搜索相关
      { "<leader>sg", desc = "实时搜索" },
      { "<leader>sw", desc = "搜索当前词" },
      { "<leader>sc", desc = "搜索命令" },
      { "<leader>sh", desc = "搜索帮助" },
      { "<leader>sk", desc = "搜索快捷键" },
      { "<leader>so", desc = "搜索选项" },
      { "<leader>sr", desc = "搜索寄存器" },
      
      -- 窗口管理
      { "<leader>ww", desc = "切换窗口" },
      { "<leader>wd", desc = "关闭窗口" },
      { "<leader>wh", desc = "左侧窗口" },
      { "<leader>wj", desc = "下方窗口" },
      { "<leader>wk", desc = "上方窗口" },
      { "<leader>wl", desc = "右侧窗口" },
      { "<leader>ws", desc = "水平分割" },
      { "<leader>wv", desc = "垂直分割" },
      { "<leader>w=", desc = "平衡窗口" },
      
      -- Git操作
      { "<leader>gc", desc = "Git提交" },
      { "<leader>gs", desc = "Git状态" },
      { "<leader>gp", desc = "Git推送" },
      { "<leader>gl", desc = "Git日志" },
      { "<leader>gb", desc = "Git分支" },
      { "<leader>gd", desc = "Git差异" },
      
      -- LaTeX功能
      { "<leader>ll", desc = "保存并编译LaTeX" },
      { "<leader>lv", desc = "查看PDF" },
      { "<leader>ls", desc = "停止编译" },
      { "<leader>lc", desc = "清理辅助文件" },
      { "<leader>le", desc = "查看错误" },
      { "<leader>lt", desc = "切换目录" },
      { "<leader>lm", desc = "数学符号列表" },
      
      -- LSP功能
      { "<leader>La", desc = "代码动作" },
      { "<leader>Ld", desc = "跳转定义" },
      { "<leader>LD", desc = "跳转声明" },
      { "<leader>Le", desc = "诊断错误" },
      { "<leader>Lf", desc = "格式化代码" },
      { "<leader>Lh", desc = "悬浮帮助" },
      { "<leader>Li", desc = "实现列表" },
      { "<leader>Lj", desc = "下一个诊断" },
      { "<leader>Lk", desc = "上一个诊断" },
      { "<leader>Ll", desc = "代码镜头" },
      { "<leader>Ln", desc = "重命名" },
      { "<leader>Lo", desc = "大纲符号" },
      { "<leader>Lr", desc = "引用列表" },
      { "<leader>Ls", desc = "文档符号" },
      { "<leader>LS", desc = "工作区符号" },
      { "<leader>Lt", desc = "类型定义" },
    },
  },
}